%% Mappa mentale - Fluid dynamics
mindmap
  root((Fluid dynamics))
    Equazioni di Eulero 1D
      Instazionario
      Forma conservativa
    Schema spazio-tempo
      Dominio di dipendenza
      Dominio di influenza
    Equazioni di compatibilita
      Invarianti di Riemann
    Equazioni iperboliche
      Autovalori reali
      u, u+a, u-a
    Linee caratteristiche
      Propagazione segnali
      Velocita finita
    Rankine-Hugoniot
      Salto attraverso urto
      Discontinuita
    Modelli
      Scalare lineare advezione
      Scalare non lineare Burgers
      Vettoriale lineare acustica
